# Generated by Django 2.1 on 2019-05-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4095)),
                ('money', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images/book_image')),
                ('introduction', models.CharField(max_length=4095, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=4095, null=True)),
                ('phonetic', models.CharField(max_length=4095, null=True)),
                ('definition', models.CharField(max_length=4095, null=True)),
                ('translation', models.CharField(max_length=4095, null=True)),
                ('exchange', models.CharField(max_length=4095, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grasped', models.BooleanField(default=False)),
                ('grasppercent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=4095)),
                ('money', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='images/user_image')),
                ('gender', models.CharField(default='保密', max_length=4)),
                ('introduction', models.CharField(max_length=4095, null=True)),
                ('studycount', models.IntegerField(default=20)),
                ('reviewcount', models.IntegerField(default=20)),
                ('activemode', models.IntegerField(default=0)),
                ('activebook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Book')),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en', models.CharField(max_length=4095)),
                ('ch', models.CharField(max_length=4095)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
            ],
        ),
        migrations.AddField(
            model_name='studyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='studyword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Word'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Word'),
        ),
    ]
